/*
 * Created on 17.05.2005
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
package das.controller;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author Arash
 *
 * TODO To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
public class AllergienServlet extends HttpServlet {
/**
 * steuerzentrale .. hier wird anhand der requests entschieden
 * welche funktionen ausgeführt werden sollen 
 */
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		//TODO Method stub generated by Lomboz
	}
	/**
	 * steuerzentrale .. hier wird anhand der requests entschieden
	 * welche funktionen ausgeführt werden sollen 
	 */
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		//TODO Method stub generated by Lomboz
	}
	/**
	 * fügt neue allergien in die datenbank ein
	 * TODO parameter festlegen
	 */
	protected void createAllergie() {
		
	}
	/**
	 * löscht allergien aus der datenbank
	 * TODO parameter festlegen
	 */
	protected void deleteAllergie() {
		
	}
	/**
	 * updated daten einer allergie in der datenbank
	 * TODO parameter festlegen
	 */
	protected void updateAllergie() {
		
	}
}
