
package das.controller;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * TODO To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
public class ZutatenServlet extends HttpServlet {
	/**
	 * steuerzentrale .. hier wird anhand der requests entschieden
	 * welche functionen ausgeführt werden sollen*/
	public void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		//TODO Method stub generated by Lomboz
	}
	/**
	 * steuerzentrale .. hier wird anhand der requests entschieden
	 * welche functionen ausgeführt werden sollen
	 */
	public void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		//TODO Method stub generated by Lomboz
	}
	/**
	 * kategorien für zutaten erstellen
	 * TODO parameter festlegen
	 */
	private void addKategorie() {
		
	}
	/**
	 * zutaten erstellen
	 * TODO parameter festlegen
	 *
	 */
	private void addZutaten() {
		
	}
	/**
	 * bearbeitet Zutaten: Kalorienwerte, etc..
	 * TODO parameter festlegen
	 */
	private void editZutaten() {
		
	}
	/**
	 * Zutaten einer kategorie zuweisen
	 * TODO parameter festlegen
	 */
	private void assignZutatenToKategorie() {
		
	}
}
